project:
  type: book

book:
  title: "QuartoTest"
  author: "JuliaHub & MIT"
  date: "11/17/202"
  chapters:
    - index.qmd
    - part: "Technical Computing"
      chapters: 
        - intro.qmd
        - optimize.qmd
        - sciml.qmd
    - part: "Parallel Computing"
      chapters:
        - dynamical_systems.qmd
        - parallelism_overview.qmd
        - styles_of_parallelism.qmd
        - discretizing_odes.qmd
    - part: "Automatic Differentiation"
      chapters: 
        - automatic_differentiation.qmd
        - stiff_odes.qmd
  appendices: 
      - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: slate
  pdf:
    documentclass: scrreprt

jupyter: scimlbook-1.8

execute:
  cache: true